name: 최근 기록 갱신
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://kj84xen.tistory.com/rss"
          max_post_count: 5
          committer_username: kj84xen
          committer_email: hkj1984@gmail.com
